name: Docs Linting

on:
  workflow_call:
    inputs:
      run-md-lint:
        description: 'Whether to run the Markdown linting job'
        required: false
        default: true
        type: boolean
      run-spelling:
        description: 'Whether to run the Spelling check job'
        required: false
        default: true
        type: boolean
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-md:
    name: "Markdown"
    runs-on: ubuntu-latest
    if: ${{ inputs.run-md-lint }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch config
        shell: sh
        run: |
          test -f .markdownlint.yaml && echo "Using local config file" || curl --silent --show-error --fail --location https://raw.github.com/ROCm/rocm-docs-core/develop/.markdownlint.yaml -O
      - name: Use markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v10.0.1
        with:
          globs: "**/*.md"

  spelling:
    name: "Spelling"
    runs-on: ubuntu-latest
    if: ${{ inputs.run-spelling }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch config
        if: ${{ ! contains( github.repository, 'rocm-docs-core') }}
        shell: sh
        run: |
          curl --silent --show-error --fail --location https://raw.github.com/ROCm/rocm-docs-core/develop/.spellcheck.yaml -O
          curl --silent --show-error --fail --location https://raw.github.com/ROCm/rocm-docs-core/develop/.wordlist.txt >> .wordlist.txt
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.30.0
      - name: On fail
        if: failure()
        run: |
          echo "Please check for spelling mistakes or add them to '.wordlist.txt' in either the root of this project or in rocm-docs-core."
